import ale.server.ale.calculations.AssignmentsCalculations;
import ale.server.models.AssignmentFourResult;
import ale.server.models.AssignmentThreeResult;
import ale.server.models.AssignmentTwoResult;
import ale.server.models.Formula;
import com.sun.xml.internal.bind.v2.TODO;
import org.junit.Test;

import java.util.List;
import java.util.Map;

import static org.hamcrest.Matchers.is;
import static org.junit.Assert.assertThat;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;


/**
 * Testing will be applied by first generating the disjunctive normal form. Second, the normal form will be passed for truth table generation
 * Third, the actual test will be comparison with the truth table generated by the initial formula and the one from the normal form(they are supposed to match)
 */
public class DisjunctiveNormalFormTest {

    @Test
    public void disjunctiveNormalFormGenerationFormula1() {
        // Initialization
        Formula initialTestFormula = mock(Formula.class);
        when(initialTestFormula.getFormula()).thenReturn(">(A,B)");

        AssignmentsCalculations assignmentsCalculations = new AssignmentsCalculations(initialTestFormula);

        // Retrieving the disjunctive normal form
        AssignmentFourResult assignmentFourResult = assignmentsCalculations.generateAssignmentFourResult();
        String disjunctiveNormalFormTruthTable = assignmentFourResult.getDisjunctiveNormalFormTruthTable();

        // Retrieving of the truth table for the initial formula
        AssignmentTwoResult assignmentTwoResultInitialFormula = assignmentsCalculations.generateAssignmentTwoResult();
        List<Map<Character, Integer>> tableResultInitialFormula = assignmentTwoResultInitialFormula.getTableResults();

        // Generate new truthTable based on the disjunctive normal form
        Formula normalFormFormula = mock(Formula.class);
        when(normalFormFormula.getFormula()).thenReturn(disjunctiveNormalFormTruthTable);

        assignmentsCalculations = new AssignmentsCalculations(normalFormFormula);

        AssignmentTwoResult assignmentTwoResultNormalFormula = assignmentsCalculations.generateAssignmentTwoResult();
        List<Map<Character, Integer>> tableResultNormalFormula = assignmentTwoResultNormalFormula.getTableResults();


        assertThat(tableResultInitialFormula, is(tableResultNormalFormula));
    }

    @Test
    public void disjunctiveNormalFormGenerationFormula2() {
        // Initialization
        Formula initialTestFormula = mock(Formula.class);
        when(initialTestFormula.getFormula()).thenReturn("~(&(>(&(A,C)),~(&(~(B),C))))");

        AssignmentsCalculations assignmentsCalculations = new AssignmentsCalculations(initialTestFormula);

        // Retrieving the disjunctive normal form
        AssignmentFourResult assignmentFourResult = assignmentsCalculations.generateAssignmentFourResult();
        String disjunctiveNormalFormTruthTable = assignmentFourResult.getDisjunctiveNormalFormTruthTable();

        // Retrieving of the truth table for the initial formula
        AssignmentTwoResult assignmentTwoResultInitialFormula = assignmentsCalculations.generateAssignmentTwoResult();
        List<Map<Character, Integer>> tableResultInitialFormula = assignmentTwoResultInitialFormula.getTableResults();

        // Generate new truthTable based on the disjunctive normal form
        Formula normalFormFormula = mock(Formula.class);
        when(normalFormFormula.getFormula()).thenReturn(disjunctiveNormalFormTruthTable);

        assignmentsCalculations = new AssignmentsCalculations(normalFormFormula);

        AssignmentTwoResult assignmentTwoResultNormalFormula = assignmentsCalculations.generateAssignmentTwoResult();
        List<Map<Character, Integer>> tableResultNormalFormula = assignmentTwoResultNormalFormula.getTableResults();


        assertThat(tableResultInitialFormula, is(tableResultNormalFormula));
    }

    @Test
    public void disjunctiveNormalFormGenerationFormula3() {
        // Initialization
        Formula initialTestFormula = mock(Formula.class);
        when(initialTestFormula.getFormula()).thenReturn("&(>(|(A,~(B)),C),A)");

        AssignmentsCalculations assignmentsCalculations = new AssignmentsCalculations(initialTestFormula);

        // Retrieving the disjunctive normal form
        AssignmentFourResult assignmentFourResult = assignmentsCalculations.generateAssignmentFourResult();
        String disjunctiveNormalFormTruthTable = assignmentFourResult.getDisjunctiveNormalFormTruthTable();

        // Retrieving of the truth table for the initial formula
        AssignmentTwoResult assignmentTwoResultInitialFormula = assignmentsCalculations.generateAssignmentTwoResult();
        List<Map<Character, Integer>> tableResultInitialFormula = assignmentTwoResultInitialFormula.getTableResults();

        // Generate new truthTable based on the disjunctive normal form
        Formula normalFormFormula = mock(Formula.class);
        when(normalFormFormula.getFormula()).thenReturn(disjunctiveNormalFormTruthTable);

        assignmentsCalculations = new AssignmentsCalculations(normalFormFormula);

        AssignmentTwoResult assignmentTwoResultNormalFormula = assignmentsCalculations.generateAssignmentTwoResult();
        List<Map<Character, Integer>> tableResultNormalFormula = assignmentTwoResultNormalFormula.getTableResults();


        assertThat(tableResultInitialFormula, is(tableResultNormalFormula));
    }

    /**
     * Here I retrieve the normal form for the simplified truth table
     * Then I generate a new truth table based on it
     * And I compare it with the simplified formurmal for from the truth table
     */
    //TODO: Check it again
    @Test
    public void disjunctiveNormalFormGenerationForSimplifiedTruthTable() {
        // Initialization
        Formula initialTestFormula = mock(Formula.class);
        when(initialTestFormula.getFormula()).thenReturn("&(=(A,B),|(C,D))");

        AssignmentsCalculations assignmentsCalculations = new AssignmentsCalculations(initialTestFormula);

        // Retrieving the disjunctive normal form for the SIMPLIFIED table
        AssignmentFourResult assignmentFourResult = assignmentsCalculations.generateAssignmentFourResult();
        String disjunctiveNormalFormSimplifiedTruthTable = assignmentFourResult.getDisjunctiveNormalFormSimplifiedTruthTable();

        // Retrieving of the SIMPLIFIED truth table for the initial formula
        AssignmentThreeResult assignmentTwoResultInitialFormula = assignmentsCalculations.generateAssignmentThreeResult();
        List<Map<Character, Character>> simplifiedTableResultInitialFormula = assignmentTwoResultInitialFormula.getSimplifiedTableResults();

        // Generate new truthTable based on the disjunctive normal form
        Formula normalFormFormula = mock(Formula.class);
        when(normalFormFormula.getFormula()).thenReturn(disjunctiveNormalFormSimplifiedTruthTable);

        assignmentsCalculations = new AssignmentsCalculations(normalFormFormula);

        AssignmentThreeResult assignmentThreeResultNormalFormula = assignmentsCalculations.generateAssignmentThreeResult();
        List<Map<Character, Character>> SimplifiedTableResultNormalFormula = assignmentThreeResultNormalFormula.getSimplifiedTableResults();


        assertThat(simplifiedTableResultInitialFormula, is(SimplifiedTableResultNormalFormula));
    }

}
